'use strict';

export default {
    TOGGLE_TODO: 'TOGGLE_TODO',
    DESTROY_TODO: 'DESTROY_TODO',
    ADD_TODO: 'ADD_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    TOGGLE_ALL: 'TOGGLE_ALL',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',

    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}